version: 0.2

env:
  secrets-manager:
    DB_HOST: arn:aws:secretsmanager:ap-southeast-1:474717861439:secret:env-WzmthE:DB_HOST
    DB_USER: arn:aws:secretsmanager:ap-southeast-1:474717861439:secret:env-WzmthE:DB_USER

phases:
  install:
    commands:
      - echo install serverless framework
      - npm install -g serverless
  pre_build:
    commands:
      - echo install pre build commands
      - npm install
  build:
    commands:
      - echo deployment started `date`
      - echo deploy serverless framework custom codebase
      - sls deploy
  post_build:
    commands:
      - echo post build completed on `date`
